Repository Azure/data-product-analytics, pull requests merged in 2021-12, with the labels that each got.

#110 Make SQL Pool Deployment Optional
  docs/reference/portal.dataProduct.json
  infra/main.bicep
  infra/main.json
  infra/modules/services/synapse.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: feature, committed

#111 Bug Fix
  infra/main.json
  infra/modules/services/machinelearning.bicep
Labels: bug

#108 Rename from ESA to DMA
  .github/workflows/lint.yml
  README.md
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-CreateRepository.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/DataManagementAnalytics-KnownIssues.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/DataManagementAnalytics-ServicePrincipal.md
  docs/images/DataManagementAnalytics.gif
  docs/images/EnterpriseScaleAnalytics.gif
  docs/reference/portal.dataProduct.json
  infra/main.bicep
  infra/main.json
Labels: documentation, committed

#112 New Issue/PR Templates & New Contributors Guide
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION_ISSUE.yml
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/linters/.textlintrc
  CONTRIBUTING.md
  README.md
Labels: documentation, committed

#113 Improving Region Availability
  .github/linters/.arm-ttk.psd1
  docs/DataManagementAnalytics-Prerequisites.md
  docs/reference/portal.dataProduct.json
  infra/main.json
  infra/modules/services/applicationinsights.bicep
  infra/modules/services/datafactory.bicep
  infra/modules/services/machinelearning.bicep
  infra/modules/services/synapse.bicep
Labels: enhancement, committed
