Repository Azure/data-product-analytics, pull requests merged in 2021-11, with the labels that each got.

#101 Updated Codeowners
  .github/CODEOWNERS
Labels: enhancement, committed

#103 Updated Azure CLI Version
  .github/workflows/dataProductDeployment.yml
Labels: bug, committed

#104 updated docs for ADO and GitHub deployments; added upticks
  docs/EnterpriseScaleAnalytics-AzureDevOpsDeployment.md
  docs/EnterpriseScaleAnalytics-GitHubActionsDeployment.md
Labels: documentation

#105 Azure CLI Action Bugfix
  .github/workflows/dataProductDeployment.yml
Labels: bug, committed

#106 Updated Portal UI based on Feedback
  docs/reference/portal.dataProduct.json
Labels: feature, committed
