Repository Azure/data-product-analytics, pull requests merged in 2022-04, with the labels that each got.

#123 Added Monitoring Capabilities (Observability-as-code)
  docs/DataManagementAnalytics-AzureDevOpsDeployment.md
  docs/DataManagementAnalytics-GitHubActionsDeployment.md
  docs/reference/portal.dataProduct.json
  infra/main.bicep
  infra/main.json
  infra/modules/services/alerts.bicep
  infra/modules/services/dashboard.bicep
  infra/modules/services/datafactory.bicep
  infra/modules/services/diagnosticsettings.bicep
  infra/modules/services/loganalytics.bicep
  infra/modules/services/synapse.bicep
  infra/params.dev.json
  infra/params.prod.json
  infra/params.test.json
Labels: feature

#127 Update DMA to Cloud-scale analytics
  CONTRIBUTING.md
  README.md
  docs/DataManagementAnalytics-Prerequisites.md
  docs/reference/portal.dataProduct.json
Labels: documentation

#130 Update Gif to Cloud-Scale Analytics
  README.md
  docs/images/CloudScaleAnalytics.gif
  docs/images/DataManagementAnalytics.gif
Labels: documentation

#129 Setting alert threshold
  infra/main.json
  infra/modules/services/alerts.bicep
Labels: bug
